spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application:
    name: microservicecloud-config-lianxi-dev
---
spring:
  profiles: test    #测试环境
  application:
    name: microservicecloud-config-lianxi-test
    #请保留UTF-8格式  
  
